# Geometry =====================================================================
/Source/Capsule/Construct
/NaI/setZ 102 cm

# Processes ====================================================================

# Produce Auger electrons and X-rays
/process/em/auger true

# Initialize run manager =======================================================
/run/initialize

# Initialize the source ========================================================
/gun/particle ion
/gun/ion 55 137

/run/beamOn 10000

/analysis/write
/analysis/closeFile