# Macro file for the initialization of the application
# in interactive session

# Set some default verbose
/control/verbose 0
#/control/saveHistory
/run/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1
#/run/printProgress 100
#/tracking/verbose 1

###############################Physics commands#################################

# physics commands should be called before initialization
#Normally, PhotonSD does not called automatically when the boundary status is 
#detection
/process/optical/boundary/setInvokeSD true

#defult type = all
#/process/setVerbose verbose type 
#/process/activate procName particle(default all) 
#/process/inactivate procName particle(default all) 

#/process/optical/boundary/verbose 2
#/process/optical/verbose 2

#name may be one of Cerenkov, Scintillation, OpAbsorption, OpRayleigh, OpMieHG, 
#OpBoundary, OpWLS,OWLS2. By default, all the processes are activated.

/process/optical/processActivation OpAbsorption true
/process/optical/processActivation OpRayleigh true
/process/optical/processActivation Scintillation true
/process/optical/processActivation Cerenkov true

#scintillation
#/process/optical/scintillation/setByParticleType false
#/process/optical/scintillation/setTrackInfo false
#/process/optical/scintillation/setFiniteRiseTime false
#/process/optical/scintillation/verbose verbose


################################################################################

# Initialize kernel
/run/initialize

###################Primary particle commands###################################

/gps/particle neutron
/gps/number 1
/gps/pos/centre 0.0 0.0 0.0
/gps/energy 1 MeV
/run/setCutForAGivenParticle proton 0.5 um

# Debugging 
#/tracking/verbose 3

# Define the zone where the neutrons will be shot
/gps/ang/type iso
/gps/ang/mintheta 178.545001 deg

################################################################################

# Visualization setting
/control/execute vis.mac
